MODEL:
  META_ARCHITECTURE: Baseline
  WEIGHTS: None #/ai/GROUP/zhangsan/domainReid02/logs/A/model_best.pth
  FREEZE_LAYERS: []

  BACKBONE:
    NAME: build_sam_reid
    NORM: BN
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 1024
    WITH_IBN: False
    PRETRAIN: True
    POINT_PROMPT: True
    BOX_PROMPT: False
    PRETRAIN_PATH: /ai/GROUP/zhangsan/sam_vit_b_01ec64.pth
    LAYER_FILTER: [0,1,2,3]
    WEIGHT_LAMBDA: 1.0

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: Identity
    NECK_FEAT: after
    CLS_LAYER: CircleSoftmax
    NUM_CLASSES: 0
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss", "HintLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

    HINT:
      LAMBDA: 1.0
      NUM_BLOCKS: 9

INPUT:
  SIZE_TRAIN: [ 384, 192 ]
  SIZE_TEST: [ 384, 192 ]

  REA:
    ENABLED: False
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True

  AUTOAUG:
    ENABLED: True
    PROB: 0.5

  CJ:
    ENABLED: True

  AUGMIX:
    ENABLED: true
    PROB: 0.5

DATALOADER:
  SAMPLER_TRAIN: SHS
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 60
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  IMS_PER_BATCH: 256
  NESTEROV: True
  SCHED: CosineAnnealingLR
  ETA_MIN_LR: 1e-6
  FREEZE_ITERS: 500
  
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 90

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 1024

CUDNN_BENCHMARK: True

DATASETS:
  NAMES: ("Market1501","cuhkSYSU","CUHK03")
  TESTS: ("MSMT17",)
  COMBINEALL: False

OUTPUT_DIR: logs/debug
